<?php

namespace App\Services\Logistics\Contracts;

use App\Models\Shipment;

interface CourierProvider
{
    /**
     * Human readable provider name.
     */
    public function name(): string;

    /**
     * Whether this provider is currently enabled.
     */
    public function enabled(): bool;

    /**
     * Create a shipment with the courier.
     *
     * Returns provider-specific metadata required for future operations.
     */
    public function createShipment(Shipment $shipment): array;

    /**
     * Cancel a shipment with the courier.
     *
     * Returns the latest provider metadata after cancellation.
     */
    public function cancelShipment(Shipment $shipment): array;

    /**
     * Fetch the latest tracking information from the courier.
     *
     * This method must not mutate application state.
     * It simply returns normalized provider data that will later be
     * consumed by TrackingSynchronizer → OrderStatusEngine.
     */
    public function trackShipment(Shipment $shipment): array;

    /**
     * Download or retrieve the shipping label.
     *
     * Returns provider-specific metadata (URL, binary reference, etc.).
     */
    public function shippingLabel(Shipment $shipment): array;

    /**
     * Download or retrieve the invoice generated by the courier,
     * if supported.
     */
    public function invoice(Shipment $shipment): array;

    /**
     * Schedule pickup with the courier.
     */
    public function schedulePickup(Shipment $shipment): array;

    /**
     * Returns true if the provider supports live tracking.
     */
    public function supportsTracking(): bool;

    /**
     * Returns true if shipment creation is supported.
     */
    public function supportsShipmentCreation(): bool;

    /**
     * Returns true if pickup scheduling is supported.
     */
    public function supportsPickupScheduling(): bool;

    /**
     * Returns true if shipment cancellation is supported.
     */
    public function supportsCancellation(): bool;
}
